### ISSUE TITLE
Return form info along with prakriyA?

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#10]
Does the database store some info regarding the form as well? E.g. jagAma = gam, liT, pra. pu., eka; gam, liT, utt. pu., eka.

This would be useful info, and it would be nice to show this description of the form in the UI title for each prakriyA result instead of just Prakriya 1, 2, ...,

**Comment by drdhaval2785** [comment]
https://api.sanskritworld.in/#!/default/get_full_data

This API has the detais you talked about. There may be some more like links to various online resources for this form. You can take a look and decide whether this API is fine for you or not. The only item missing in this API is the text of sUtra. It has only sUtra number. I can fix it if you want (and it would be better for other users too). That ways, I give you all that I have to offer and you can decide where to display what from it.

**Comment by avinashvarna** [comment]
Yes! That would be excellent! That way, everything can be fetched at once, and then the UI can let the user choose what to display. This would also apply to other applications, to use the subset they need, and use the other API if only the prakriyA is needed.

I noticed that https://api.sanskritworld.in/v0.0.2/jagAma has the lakAra, but not puruSha and vacana. Can that be added as well?

**Comment by drdhaval2785** [comment]
> not puruSha and vacana

I also realised it after the data was generated and put in API. The first thing a person wants to know is the verb, tense, puruSa and vacana.

In capturing the data, I forgot to store the suffix. So as of now I do not have puruSa, vacana details. Will regenerate data.

**Comment by drdhaval2785** [comment]
So I am going to keep prakriya API as it is.
Will just change the get_full_data API to give everything the user wants.
UI can be built on that.

**Comment by drdhaval2785** [comment]
@avinashvarna 
The API is ready now.
See https://api.sanskritworld.in/v0.0.2/verbforms/slp1/Bavati?output_transliteration=devanagari

**Comment by drdhaval2785** [comment]
Will keep this open till the UI is updated to v0.0.2 path changes in UI.

**Comment by avinashvarna** [comment]
I've updated the UI to query the API that returns full data and display most of the information correctly.

**Comment by avinashvarna** [comment]
Looks like the "verb" field in the response is not getting transliterated. E.g. when output_transliteration is HK:
https://api.sanskritworld.in/v0.0.2/verbforms/slp1/jagAma?output_transliteration=hk

**Comment by drdhaval2785** [comment]
verb - associated with accents, so not quite possible to transliterate.
verbslp - in slp1. Not necessary to transliterate.
various links - ignore in transliteration.

**Comment by drdhaval2785** [comment]
As the API for frontend is now shifted to more verbose API, time to close this issue.
The dangling issue regarding transliteration is shifted to separate issue 22.
