### ISSUE TITLE
चचाल prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#101]
https://ashtadhyayi.com/dhatu/01.0924?form=%E0%A4%9A%E0%A4%B2%E0%A4%A4%E0%A4%BF
०१.०९२४ चल्
चचाल prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
@neeleshb may look into it.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0924&tab=tin handles this.
