### ISSUE TITLE
इयष्ठ prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#104]
https://ashtadhyayi.com/dhatu/01.1157?form=%E0%A4%AF%E0%A4%9C%E0%A4%A4%E0%A4%BF
०१.११५७ यज्
इयष्ठ prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.1157&tab=tin handles this.
