### ISSUE TITLE
कन्दावहे prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#105]
https://ashtadhyayi.com/dhatu/01.0878?form=%E0%A4%95%E0%A4%A8%E0%A5%8D%E0%A4%A6%E0%A4%A4%E0%A5%87
०१.०८७८ कन्द्
कन्दावहे prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
API functional. @neeleshb may like to investigate at his end.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0878&tab=tin handles this.
