### ISSUE TITLE
चक्लन्दिध्वे prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#106]
https://ashtadhyayi.com/dhatu/01.0880?form=%E0%A4%95%E0%A5%8D%E0%A4%B2%E0%A4%A8%E0%A5%8D%E0%A4%A6%E0%A4%A4%E0%A5%87
०१.०८८० क्लन्द्
चक्लन्दिध्वे prakriya is not loading.
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
API response for https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/%E0%A4%9A%E0%A4%95%E0%A5%8D%E0%A4%B2%E0%A4%A8%E0%A5%8D%E0%A4%A6%E0%A4%BF%E0%A4%A7%E0%A5%8D%E0%A4%B5%E0%A5%87?output_transliteration=devanagari is correct. @neeleshb may like to investigate at his end.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0880&tab=tin handles this.
