### ISSUE TITLE
स्थगामि prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#109]
https://ashtadhyayi.com/dhatu/01.0899?form=%E0%A4%B8%E0%A5%8D%E0%A4%A5%E0%A4%97%E0%A4%A4%E0%A4%BF
०१.०८९९ स्थग्
स्थगामि prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0909 handles this. I am not sure why the number change in the verb though.
