### ISSUE TITLE
500 Internal errors

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#11]
https://api.sanskritworld.in/v0.0.2/input/slp1/output/slp1/BUyAH/prakriya/machine returns 500. 

I experience the same issue with भूयास्ताम्, क्रियात्.

**Comment by drdhaval2785** [comment]
Thanks for the pointer. It seems that ASIrliN forms of all dhAtus are
missing.
Will see why this happenned and what can be done as corrective step.

**Comment by drdhaval2785** [comment]
[Sun Dec 17 05:35:10.651315 2017] [wsgi:error] [pid 15570] [client 117.204.213.177:10429] KeyError: u'3.1.173', referer: https://api.sanskritworld.in/

It seems that 3.1.173 key is absent in sutrainfo.json and still present in derivation.
Will check.

**Comment by drdhaval2785** [comment]
Got the error
```
/* AziSi liGlowau (3.3.173) */
if (in_array($so,$tiG) && $pada==="pratyaya" && $lakAra==="ASIrliN")
{
	storedata('3.1.173','sa',0);
}
```
Typo resulted in 3.1.173 being stored instead of 3.3.173.
Corrected in SanskritVerb repo. Will regenerate the forms.

**Comment by drdhaval2785** [comment]
This calls for a thorough inspection of the files for the keys being absent in sutrainfo.json.

**Comment by drdhaval2785** [comment]
The error is sorted out. Notice in UI may be removed now
