### ISSUE TITLE
सस्नुः prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#110]
https://ashtadhyayi.com/dhatu/02.0047?form=%E0%A4%B8%E0%A5%8D%E0%A4%A8%E0%A4%BE%E0%A4%A4%E0%A4%BF
०२.००४७ स्ना
सस्नुः prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0047 handles this.
