### ISSUE TITLE
श्रााव prakriya is not loading.

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#111]
https://ashtadhyayi.com/dhatu/01.0922?form=%E0%A4%B6%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%A4%E0%A4%BF
०१.०९२२ श्रा
श्रााव prakriya is not loading.
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
Double 'AA' is illegal in Sanskrit. @neeleshb to correct.

**Comment by drdhaval2785** [comment]
@neeleshb has corrected it, it seems. https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0922 also handles this.
