### ISSUE TITLE
अधीयन्ति prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#112]
https://ashtadhyayi.com/dhatu/02.0042?form=%E0%A4%85%E0%A4%A7%E0%A5%8D%E0%A4%AF%E0%A5%87%E0%A4%A4%E0%A4%BF
०२.००४२ इ
अधीयन्ति prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0042 handles this.
