### ISSUE TITLE
तुवीवः prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#118]
https://ashtadhyayi.com/dhatu/02.0029?form=%E0%A4%A4%E0%A4%B5%E0%A5%80%E0%A4%A4%E0%A4%BF
०२.००२९ तु
तुवीवः prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0029 handles this.
