### ISSUE TITLE
Wrong choice of candrabindu early in life

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#12]
When I started to code SanskritVerb, I didnt read SLP1 specs properly and decided that it does not have a candrabindu. So I decided to use '!' for it. But correct choice is '~'. Now it is too difficult to change code internals. But during storage / emitting out / API calls, I think I should convert ! to ~.

**Comment by drdhaval2785** [comment]
![screenshot_20171217-065211](https://user-images.githubusercontent.com/5755132/34075784-5cda0910-e2f7-11e7-9d3c-d35c48318141.png)

See the error in transliteration here. Because I gave wrong letter.

**Comment by avinashvarna** [comment]
I've temporarily fixed it in the UI (https://avinashvarna.github.io/prakriya/). We can fix it in the main module later.

**Comment by avinashvarna** [comment]
The verbslp field of the results in
https://api.sanskritworld.in/v0.0.2/verbforms/slp1/jagAma?output_transliteration=devanagari
still has "!" instead of chandrabindu.

**Comment by drdhaval2785** [comment]
Yes. Just saw it. Will fix in API in evening
