### ISSUE TITLE
सुष्णाव prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#120]
https://ashtadhyayi.com/dhatu/02.0033?form=%E0%A4%B8%E0%A5%8D%E0%A4%A8%E0%A5%8C%E0%A4%A4%E0%A4%BF
०२.००३३ स्नु
सुष्णाव prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0033 handles this.

**Comment by drdhaval2785** [comment]
@vshylaja I sincerely thank you for your systematic filing of bug reports and seek your pardon for not being able to handle them. Now a more robust implementation of verb forms is available at **https://ambuda-org.github.io/vidyullekha/**. So, closing the issues which are handled well at that place.
