### ISSUE TITLE
कवाम prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#124]
https://ashtadhyayi.com/dhatu/02.0037?form=%E0%A4%95%E0%A5%8C%E0%A4%A4%E0%A4%BF
०२.००३७ कु
कवाम prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0037 handles this.
