### ISSUE TITLE
अध्ययावहै prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#133]
https://ashtadhyayi.com/dhatu/02.0041?form=%E0%A4%85%E0%A4%A7%E0%A5%80%E0%A4%A4%E0%A5%87
०२.००४१ इ
अध्ययावहै prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0041 handles this.
