### ISSUE TITLE
अपृञ्जिष्यन्त prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#137]
https://ashtadhyayi.com/dhatu/02.0021?form=%E0%A4%AA%E0%A5%83%E0%A4%99%E0%A5%8D%E0%A4%95%E0%A5%8D%E0%A4%A4%E0%A5%87
०२.००२१ पृञ्ज्
अपृञ्जिष्यन्त prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0021 handles this.
