### ISSUE TITLE
अनिञ्जिष्यन्त prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#140]
https://ashtadhyayi.com/dhatu/02.0018?form=%E0%A4%A8%E0%A4%BF%E0%A4%99%E0%A5%8D%E0%A4%95%E0%A5%8D%E0%A4%A4%E0%A5%87
०२.००१८ निञ्ज्
अनिञ्जिष्यन्त prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0018 handles this.
