### ISSUE TITLE
ईडिष्यन्ते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#142]
https://ashtadhyayi.com/dhatu/02.0009?form=%E0%A4%88%E0%A4%A1%E0%A4%BE%E0%A4%A4%E0%A5%87
०२.०००९ ईड्
ईडिष्यन्ते prakriya is not loading
Please check other forms also in the same page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0009 handles this.
