### ISSUE TITLE
निंसिष्यन्ते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#151]
https://ashtadhyayi.com/dhatu/02.0017?form=%E0%A4%A8%E0%A4%BF%E0%A4%82%E0%A4%B8%E0%A5%8D%E0%A4%A4%E0%A5%87
०२.००१७ निंस्
निंसिष्यन्ते prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0017 handles this.
