### ISSUE TITLE
ब्रवै prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#155]
https://ashtadhyayi.com/dhatu/02.0039?form=%E0%A4%AC%E0%A5%8D%E0%A4%B0%E0%A4%B5%E0%A5%80%E0%A4%A4%E0%A4%BF
०२.००३९ ब्रू
ब्रवै prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0039 handles this.
