### ISSUE TITLE
दोहामहै prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#159]
https://ashtadhyayi.com/dhatu/02.0004?form=%E0%A4%A6%E0%A5%8B%E0%A4%97%E0%A5%8D%E0%A4%A7%E0%A4%BF
०२.०००४ दुह्
दोहामहै prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0004 handles this.
