### ISSUE TITLE
हास्यन्ते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#170]
https://ashtadhyayi.com/dhatu/03.0008?form=%E0%A4%9C%E0%A4%BF%E0%A4%B9%E0%A5%80%E0%A4%A4%E0%A5%87
०३.०००८ हा
हास्यन्ते prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0008 handles this.
