### ISSUE TITLE
अधास्यन्त prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#174]
https://ashtadhyayi.com/dhatu/03.0011?form=%E0%A4%A6%E0%A4%A7%E0%A4%BE%E0%A4%A4%E0%A4%BF
०३.००११ धा
अधास्यन्त prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here for अधास्यन्त
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0011 handles this.
