### ISSUE TITLE
नेक्ष्यन्ते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#178]
https://ashtadhyayi.com/dhatu/03.0012?form=%E0%A4%A8%E0%A5%87%E0%A4%A8%E0%A5%87%E0%A4%95%E0%A5%8D%E0%A4%A4%E0%A4%BF
०३.००१२ निज्
नेक्ष्यन्ते prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya Error is also reported here for नेक्ष्यन्ते
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0012 handles this.
