### ISSUE TITLE
वेक्ष्यन्ते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#179]
https://ashtadhyayi.com/dhatu/03.0013?form=%E0%A4%B5%E0%A5%87%E0%A4%B5%E0%A4%BF%E0%A4%95%E0%A5%8D%E0%A4%A4%E0%A4%83
०३.००१३ विज्
वेक्ष्यन्ते prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0013 handles this.
