### ISSUE TITLE
वेक्ष्यन्ते prakriya not loading विष्

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#180]
https://ashtadhyayi.com/dhatu/03.0014?form=%E0%A4%B5%E0%A5%87%E0%A4%B5%E0%A5%87%E0%A4%B7%E0%A5%8D%E0%A4%9F%E0%A4%BF
०३.००१४ विष्
वेक्ष्यन्ते prakriya not loading विष्
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here for वेक्ष्यन्ते
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0014 handles this.
