### ISSUE TITLE
जघृतः prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#181]
https://ashtadhyayi.com/dhatu/03.0015?form=%E0%A4%9C%E0%A4%BF%E0%A4%98%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%BF
०३.००१५ घृ
जघृतः prakriya is not loading
Please check other forms also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here for जघृतः
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0015 handles this.
