### ISSUE TITLE
ऋ गतौ जुहोत्यादि

### ISSUE THREAD

**Issue by Siva-rk** [drdhaval2785/prakriya#187]
अत्र प्रक्रियायाम् अभ्यासस्य इयङादेशः विधेयम्। परन्तु तत् अभ्यासस्यासवर्णे 6.4.78 अनेनैव भवति इति कौमुद्याम् उक्तम्। अतः प्रक्रियायाम् अन्य असम्बन्ध सूत्रस्य उल्लेखम् निवर्तनीयम्

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0017 handles this.
Thank you for the report @Siva-rk .
