### ISSUE TITLE
गा स्तुतौ जुहोत्यादि

### ISSUE THREAD

**Issue by Siva-rk** [drdhaval2785/prakriya#188]
अत्र लोटि, प्रथम-एक वचने, जिगीतात् इत्यस्य प्रक्रियायाम्, ईकारादेशः घुमास्थागापाजहातिसां हलि इत्यनेन इति  लेखितम्। परन्तु उक्त सूत्रम् आर्धधातुके एव प्रवर्तते किल, एतदपवादम् परिहरोतु

**Comment by drdhaval2785** [comment]
Pending to handle at https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=03.0026 too.
There is additional error at vidyut. Reported at https://github.com/ambuda-org/vidyut/issues/71.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=03.0026&activePada=%7B%22text%22%3A%22jigItAt%22%2C%22type%22%3A%22tinanta%22%2C%22args%22%3A%7B%22dhatu%22%3A%7B%22code%22%3A%2203.0026%22%2C%22upadesha%22%3A%22gA%5C%5C%22%2C%22upadeshaQuery%22%3A%22gA%22%2C%22artha%22%3A%22stutO%22%7D%2C%22lakara%22%3A%225%22%2C%22prayoga%22%3A0%2C%22purusha%22%3A%220%22%2C%22vacana%22%3A%220%22%2C%22pada%22%3A%220%22%2C%22sanadi%22%3Anull%2C%22upasarga%22%3Anull%7D%7D has handled it now. 

It is by "I halyaghoH" now.
