### ISSUE TITLE
धेकयति prakriya is not loading

### ISSUE THREAD

**Issue by uscasdrs** [drdhaval2785/prakriya#189]

**Comment by drdhaval2785** [comment]
@uscasdrs Thank you for the report. Kindly provide details from printed Dhatupathas where this verb occurs. It seems that this verb is not there in my database. Therefore, its forms are not generated. I have not seen any usage of this so called verb. So need to confirm with books before we can incorporate it in our database.

**Comment by uscasdrs** [comment]
It is the last धातु in ashtadhyayi.com.

Link: https://ashtadhyayi.com/dhatu/10.0492

If I click on धेकयति (प्रथमपुरुष एकवचन), I expect to see the प्रक्रिया, but
instead, I see the following message:

We are sorry, but the prakriya cannot be loaded right now.
If the dhatu-form is correct but the prakriya cannot be loaded, please
report the issue here <https://github.com/drdhaval2785/prakriya/issues>.
And if the dhatu-form is wrong, please send a feedback
<https://ashtadhyayi.com/dhatu/10.0492#feedback-modal>.

**Comment by drdhaval2785** [comment]
Confirmed with @neeleshb

The verb is taken from Siddhanta Kaumudi, it is numbered 1915 there, see the sutra 7.4.97 ई च गणः ।  कौमुदी does say "इत्येके", and कृदन्तरूपनन्दिनी clarifies क्षीरतरङ्गिणीमाधवीयधातुवृत्तिषु तु अयं धातुः न दृश्यते ।

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=10.0492 handles this.
