### ISSUE TITLE
Better machine-friendly prakriyA JSON

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/prakriya#19]
Looking at https://api.sanskritworld.in/v0.0.2/verbforms/slp1/jagAma?encoding=devanaagari -

Stuff like:
```
[
        "लः कर्मणि च भावे चाकर्मकेभ्यः।",
        "३।४।६९",
        "गम्"
]
```

Should be:
```
{
"suutra": "लः कर्मणि च भावे चाकर्मकेभ्यः।",
"suutra_num": "३।४।६९",
"form": "गम्"
}
```

It does not make semantic sense for it to be a list.

**Comment by vvasuki** [comment]
Also related are comments at https://github.com/drdhaval2785/SanskritVerb/issues/1047#issuecomment-347915690

**Comment by drdhaval2785** [comment]
Done now.
