### ISSUE TITLE
Prikriya not loading for most forms of रधिँ भाषायाम्

### ISSUE THREAD

**Issue by nangia** [drdhaval2785/prakriya#190]
On page https://ashtadhyayi.com/dhatu/10.0326, the Prakriya for १०.०३२६ रन्ध्  (रधिँ भाषायाम्, चुरादिः  उभयपदी  सकर्मकः  सेट्) most forms does not load. 

Only the following ones are getting loaded: 

लिट्लकारः (आत्मनेपदम्)
आशीर्लिङ्लकारः (परस्मैपदम्)
लुङ्लकारः (both आत्मनेपदम् and परस्मैपदम्)

**Comment by drdhaval2785** [comment]
Thanks for the report. The verb is not in our database. Kindly provide the dhaatupaatha entry of this verb.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=10.0326 handles this.
