### ISSUE TITLE
रूपसिद्धि of पा पाने धातु - लिट्, प्रथम पुरुष, द्विवचन – पपतुः

### ISSUE THREAD

**Issue by mahesh260** [drdhaval2785/prakriya#192]
Final form of पपतुः is achieved using आतो लोप इटि च 6-4-64.  But not with श्नाभ्यस्त्योरातः - 6-4-117. Thank you.

**Comment by drdhaval2785** [comment]
@mahesh260 thank you for your report. 

I am out of touch with grammar for quite some time now. Can you elaborate from commentaries why श्नाभ्यस्त्योरातः would not apply and why आतो लोप इटि च would apply. That would save me some pains of going through grammar maze.

**Comment by mahesh260** [comment]
Respected Dhaval Sir,

Namaste, I had written an email to Neelesh Sir regarding the same. He asked
me to report it to the forum.

1. श्नाभ्यस्त्योरातः - 6-4-117;  sutra applies for सर्वधातुके; but
according to लिट्‌ च – 6.4.115, परोक्षे लिट् is आर्धधातुक. This can never
be applied for लिट्‌.

2. This particular पाद of Asthadyayi, starting from 6-4-22 to 6-4-175
doesn’t work like विप्रतिषेधे परम कर्यम्, because of असिध्दवदत्राभात्‌ -
6-4-22. The sutras are mutually asiddha towards each other when it comes to
karyas with समानाश्रय. So, the final form of पपतुः is achieved using आतो
लोप इटि च 6-4-64.

Thank you very much,

Kind regards

Makesh M

Following is the response given by Neelesh Sir towards my question.

*Namaste. Thanks for the email. *
*If you are referring to the prakriya that is shown on the right side when
a dhatu-form is clicked, kindly note that the prakriya is generated using a
computer program which is neither written nor controlled by me. You can
file a bug against that program here
<https://github.com/drdhaval2785/prakriya/issues>, and their team might
take a look.*
*Regarding your question about the prakriya, you are correct, पपतुः is
derivable using आतो लोप इटि च, not using श्नाभ्यस्तयोरातः, the latter
requires a सार्वधातुकप्रत्यय.  In fact, काशिका quotes exactly this word
(पपतुः) in the vyakhya of आतो लोप इटि च. *
*One last point, it is not correct to say "पूर्वत्रं बलवान्" in the आभीय
असिद्धाधिकार. The correct statement is that the sutras are mutually asiddha
towards each other when it comes to karyas with समानाश्रय ।*

*- Neelesh*

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1074 handles this.
