### ISSUE TITLE
०२.००१२ शास् Prakriya for this Dhatu is not loading

### ISSUE THREAD

**Issue by warija** [drdhaval2785/prakriya#193]
The prakriyas for आशासे, etc all forms of शास् धातु are not available.

**Comment by drdhaval2785** [comment]
It is a typical verb. It always has an upasarga आङ् prefixed. That may be the case.
if you are interested to see derivation, you may try alternatively at this location.

You may tweak lakAra=law to other lakAras if you want.

https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=ASAsu%21&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&jsonmode=0&cond11=2&number=02.0012&removed_sutras=&step=11&type=tiGanta

**Comment by warija** [comment]
Thank you! Much appreciated...
Warija

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0012 handles this.
