### ISSUE TITLE
Page prompts to download, krit-prakriya.pdf. 

### ISSUE THREAD

**Issue by mahesh260** [drdhaval2785/prakriya#195]
Hello, every time we refresh the page https://ashtadhyayi.com/ or open any sutra, the page always prompts us to download https://ashtadhyayi.com/kridanta/krit-prakriya.pdf. Please kindly resolve this issue. Thank you.

**Comment by drdhaval2785** [comment]
Namaste,
I do not maintain ashtadhyayi.com, so I would not be able to resolve this issue. Forwarding it via email to Mr. Nilesh Bodas who maintains this site.

**Comment by mahesh260** [comment]
Thank you very much

**Comment by neeleshb** [comment]
Namaste Mahesh ji, please email me (neelesh.bodas@gmail.com) with your machine details and I will take a look. Thanks.

**Comment by mahesh260** [comment]
[image: image.png]

Hello Neelesh Sir,
This is what keeps coming. I have IDM (internet download manager), that
keeps popping up and prompts me to download the kridanta prakriya pdf file.
Every sutra that, I click on, or every page I move to, and this is
happening after you have added Kosha update for android app, as per my
notice. Thank you.  I am not sure, is this what you required ( about
machine details) .

[image: image.png]
