### ISSUE TITLE
Prakriya not loading for भुज् विधिलिङ् उत्तमपुरुष

### ISSUE THREAD

**Issue by jupiter1957** [drdhaval2785/prakriya#197]
श्री धवलमहोदयः Prakriya not loading for भुज् विधिलिङ् उत्तमपुरुषः। परेशः दलालः

**Comment by drdhaval2785** [comment]
I am not sure about the issue, because I am able to see prakriyA for both Buj

![Screenshot_20210813-091628_Chrome](https://user-images.githubusercontent.com/5755132/129302247-0c82573c-5ce5-44fc-a915-cdd3dba300b4.jpg)
![Screenshot_20210813-091559_Chrome](https://user-images.githubusercontent.com/5755132/129302252-3d61d92a-04c0-4102-9282-34ac21f54a9c.jpg)

**Comment by jupiter1957** [comment]
Dhaval Mahodaya,
Namaste,

Thank you for your prompt response. I will try again.&nbsp;Many times आत्मनेपदी forms do not load on this web site.
I am doing my self study project to write&nbsp;प्रक्रिया for Grammatical Analysis of all Slokas of Srimad Bhagawad Geeta and am stuck at Sloka 2.5
I am stuck at the last stage for उत्तमपुरुषः एकवचन प्रक्रिया . I am not sure how य् + इ of इट् can be changed to य? because the final form is भुञ्जीय. Please see my attempt below.
&nbsp;						भुजँ			पालनाभ्यवहारयोः रुधादिः&nbsp; उभयपदी&nbsp; सकर्मकः&nbsp; अनिट् - &#39;अभ्यवहारः&#39; (= भोजनम्) इत्यस्मिन् अर्थे तु आत्मनेपदी ।							भुज्			अनुबन्धलोपे							भुज्			1.3.1 भूवादयो धातवः इत्यनेन &#39;भू&#39; आदयः शब्दाः क्रियावाचिनि अर्थे धातुसंज्ञकाः भवन्ति ।							भुज्			3.4.69 लः कर्मणि च भावे चाकर्मकेभ्यः इति लकाराः सकर्मकेभ्य धातुभ्य कर्तरि कर्मणि च, तथा अकर्मकेभ्य धातुभ्य कर्तरि भावे च							भुज् + लिँङ्			3.3.161 विधिनिमन्&zwj;त्रणामन्&zwj;त्रणाधीष्टसंप्रश्नप्रार्थनेषु लिङ् इत्यनेन विधिः, निमन्त्रणम्, आमन्त्रणम्, अधीष्टम्, सम्प्रश्नः, प्रार्थना - एतेषु अर्थेषु धातोः परः आद्युदात्तः लिङ्-प्रत्ययः भवति ।							भुज् + ल्			अनुबन्धलोपे							भुज् + ल्			3.4.77 लस्य इति अधिकारोऽयम् । इतः परमस्य पादस्य परिसमाप्तिपर्यन्तमुक्तानि कार्याणि लकाराणाम् स्थाने भवन्ति ।							भुज् + तिङ्			3.4.78 तिप्तस्झिसिप्थस्थमिब्वस्मस् तातांझथासाथांध्वमिड्वहिमहिङ् इति लकारस्थाने तिङ्							भुज् + तिङ्
			भुज् + तङ्
			&nbsp;
			&nbsp;
			&nbsp;
			&nbsp;
			भुज् + इट्			1.4.99 लः परस्मैपदम्
			1.4.100 तङानावात्मनेपदम् इत्यनेन लकारस्य स्थाने विद्यमानाः तङ्-तथा आन्-आदेशाः आत्मनेपदसंज्ञकाः भवन्ति ।
			1.4.101 तिङस्त्रीणि त्रीणि प्रथममध्यमोत्तमाः इति तिङ्-प्रत्ययाः क्रमेण प्रथम-मध्यम-उत्तम-संज्ञकाः
			1.4.102 तान्येकवचनद्विवचनबहुवचनान्येकशः इति तिङ्प्रत्ययाः क्रमेण एकवचन-द्विवचन-बहुवचन-संज्ञकाः
			1.4.107 अस्मद्युत्तमः इत्यनेन यत्र अस्मद् शब्देन लकारेण च समानः पदार्थः विवक्ष्यते, तत्र उत्तमपुरुषस्य प्रत्ययाः भवन्ति ।							भुज् + इट्			3.4.113 तिङ्शित्सार्वधातुकम् इति धातुभ्यः विहिताः तिङ्-प्रत्ययाः तथा शित्-प्रत्ययाः सार्वधातुकसंज्ञकाः सन्ति ।							भुज् + शप् + इट्			3.1.68 कर्तरि शप् इति सार्वधातुके कर्तरि प्रत्यये परे धातोः परः शप्-प्रत्ययः विधीयते ।							भुज् + श्नम् + इट्			3.1.78 रुधादिभ्यः श्नम् इत्यनेन सार्वधातुके कर्तरि प्रत्यये परे रुधादिगणस्य धातोः परः श्नम्-प्रत्ययः विधीयते । अयम् प्रत्ययः धातोः अन्तिमवर्णात् पूर्वमागच्छति ।							भु + श्नम् +ज्+ सीयुट् + इट्			3.4.102 लिङस्सीयुट् इत्यनेन लिङ्-लकारस्य केवलमात्मनेपदस्य प्रत्ययानाम् विषये सीयुट्-आगमः भवति ।							भु + न + ज् + सीय् + इ			अनुबन्धलोपे सीयुट् इत्यस्य टकारः इत्संज्ञकः, उकारः उच्चारणार्थः							भु + न् + ज् + सीय + इ			6.4.111 श्नसोरल्लोपः इत्यनेन श्नम्-विकरणस्य, &#39;अस्&#39; धातोः च अङ्गस्य अकारस्य सार्वधातुके कित् / ङित् प्रत्यये परे लोपः भवति ।							भु न् ज् + ईय् + इ			7.2.79 लिङः सलोपोऽनन्त्यस्य इत्यनेन सार्वधातुक-लिङ्लकारस्य प्रत्यये यः सकारः अन्ते विद्यमानः नास्ति, तस्य लोपः भवति ।			
Thanks and Regards,
Paresh Dalal
