### ISSUE TITLE
चुरादि लिट्

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#20]
"The verb form is not in our database. If you feel it deserves to be included, kindly notify us on https://github.com/drdhaval2785/sktderivation/issues"

for चोरयामास, गणयामास, etc. Is this expected?

**Comment by drdhaval2785** [comment]
corayAYcakAra is present. corayAmAsa and corayAmbaBUva are absent. 
Known issue.
https://github.com/drdhaval2785/SanskritVerb/issues/266

**Comment by gasyoun** [comment]
> Known issue.

Pending for how long?

**Comment by drdhaval2785** [comment]
2 years
