### ISSUE TITLE
लिटि धातोरनभ्यासस्य

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/prakriya#202]
I see this prakriya - 

   {
        "sutra": "एकाचो द्वे प्रथमस्य",
        "sutra_num": "६।१।१",
        "form": "अर्च्+ण"
      },
      {
        "sutra": "लिटि धातोरनभ्यासस्य",
        "sutra_num": "६।१।८",
        "form": "अर्च्+अर्च्+ण"
      },

Actually, just the second sUtra is applied (the first is part of the anuvRtti of the second). 
As far as display is concerned, लिटि धातोरनभ्यासस्य should be shown as having been applied before एकाचो द्वे प्रथमस्य, because it selects a bigger string before एकाचो द्वे प्रथमस्य refines the selection and does the duplication.

cc @neeleshb

**Comment by drdhaval2785** [comment]
![6E389779-2A56-4394-9DA7-B89F3761891E](https://user-images.githubusercontent.com/5755132/166100791-69876782-d0cf-4e29-952d-80fdb833c9b9.png)

**Comment by drdhaval2785** [comment]
The ones in green are ‘non-vidhi’ rules. The ones in grey are vidhi rules.

Just as halantyam provides info on which letter is to be removed and tasya lopaH removes the letter,

ekAcho dce prathamasya provides info on what is to be duplicated and liTi dhAtoranabhyAsasya duplicates.

**Comment by vvasuki** [comment]
Ok - that makes sense. Will open a separate issue about updating they babylon dict.
