### ISSUE TITLE
अनुप्रयोगे लिट् - प्रक्रिया doesn't load

### ISSUE THREAD

**Issue by jayakum108** [drdhaval2785/prakriya#205]
In 
https://ashtadhyayi.com/dhatu/01.0461?type=ting
गुप् धातु
लिट्
III/1 forms जुगोप , गोपायाञ्चकार , गोपायाम्बभूव , गोपायामास are all correct.
प्रक्रियाs for गोपायाञ्चकार loads but not the others.
Likewise,
पठ्, णिजन्ते (पाठि)
लिट्
पाठयाञ्चकार , पाठयामास , पाठयाम्बभूव, etc.
None of the प्रक्रियाs load.

**Comment by drdhaval2785** [comment]
It is a known problem. It was consciously decided to give prakriya for only one form. Storing / giving prakriya for all forms would take up a lot of space.

**Comment by jayakum108** [comment]
Thank you.
And I presume that on the णिजन्ते tab,
No prakriyas for any of the लकारा: will load at the moment.

**Comment by drdhaval2785** [comment]
I agree.
