### ISSUE TITLE
अरुणःप्रक्रिया

### ISSUE THREAD

**Issue by sainaviya** [drdhaval2785/prakriya#206]
अरुणःप्रक्रिया  cannot be loaded.

**Comment by sridharb1** [comment]
(७.१) रुध्-धातोः लङ्-लकारः मध्यमपुरुषः एकवचनम् त्रीणि रूपाणि भविष्यन्ति - अरुणत्/अरुणद्/अरुणः
तत्र अरुणः रूपस्य प्रक्रिया न आगच्छति

प्रायः समान भिद्-धातोः त्रीणि रूपाणि अभिनत्, अभिनद्, अभिनः आगच्छन्ति, किमर्थम्

**Comment by drdhaval2785** [comment]
@neeleshb may like to throw some light on grammatical tradition in this case.

**Comment by drdhaval2785** [comment]
@mrudani may also like to clarify her views on this point.

**Comment by sridharb1** [comment]
उदाहरणार्थं अहं प्रक्रियां दर्शयामि

[रुध्.pdf](https://github.com/drdhaval2785/prakriya/files/11109402/default.pdf)

**Comment by drdhaval2785** [comment]
I understand the derivation shown by you. Only issue is whether “dh” converted to “d” would qualify for “dashcha” or does it require the root to originally have “d” at the end.

**Comment by sridharb1** [comment]
Ok, please do find out. However, I can say that in addition to ashtadhyayi.com, the same is also shown in Sowmya Krishnapur's दशगणिप्रक्रिया vyoma/online course that I am following at the moment.

![image](https://user-images.githubusercontent.com/13346687/228836657-b4a026b9-5be7-41e8-a225-bcfb31d82d3c.png)

**Comment by mrudani** [comment]
दश्च इति सूत्रं धातो: दकारस्य इति उक्तम्, स: दकार: उपदेशे भवेदिति नोक्तम्।
अत: जश्त्वेन दकारे तस्य रुत्वं भेदिति ज्ञायते।

**Comment by sainaviya** [comment]
Ram Ram Ram sir,

धनयवादाः
The prakriya for अरुणः is not uploaded in ashtadhyayi.com. That was what  I
wanted to communicate.
Thanks for the explanation.

Thanks and Regards,
Sainaviya.
