### ISSUE TITLE
अनुदत प्रक्रिया न प्राप्तम्

### ISSUE THREAD

**Issue by sridharb1** [drdhaval2785/prakriya#207]
![image](https://user-images.githubusercontent.com/13346687/227429412-fe096609-9ae4-4c7a-b4ef-f7c13a12bf75.png)

कृपया स्पष्टी करोतु

धन्यवादः
श्रीधरः

**Comment by drdhaval2785** [comment]
I think that the issue has arises because I had treated this root as parasmaipadi only, whereas ashtadhyayi.com has treated it as ubhayapadi. Therefore, there are no Atmanepadi forms stored in my system. Hope this helps.

**Comment by sridharb1** [comment]
Sorry, it doesn't help. 🙂

It is either परस्मैपदी or उभयपदी. Are you claiming that it is the former? If so, we can initiate a discussion with ashtadyayi.com. Otherwise, it needs to be fixed here.

Thanks.

**Comment by drdhaval2785** [comment]
There are two णुद roots. One ubhayapadi and one parasmaipadi.

![F6EF9BEC-610C-4511-BF9B-8B7511A74F01](https://user-images.githubusercontent.com/5755132/227689677-03a04c30-d738-40ed-9d96-5fa0f0567966.jpeg)

If you click on the later, you may get the derivation you are looking for.

note - there is a difference in the root database being used by me and ashtadhyayi.com. 
In the data which I used, the first entry 06.0002 is parasmaipadi and the other entry is ubhayapadi.

In ashtadhyayi.com, it is reversed. 

I would appreciated if you can go through the dhatupatha and decide which is correct.

**Comment by sridharb1** [comment]
Thank you for the explanation - this helps. 🙂

**Comment by sridharb1** [comment]
I have created an issue on ashtadhyayi.com for further resolution.
