### ISSUE TITLE
भोक्ष्यते prakriya not loaded. Pl load it now.

### ISSUE THREAD

**Issue by lakshmibsnt** [drdhaval2785/prakriya#208]

**Comment by drdhaval2785** [comment]
pending to handle at https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=07.0017.
In meaning of food, this root seems to be AtmanepadI as per ashtadhyayi.com.

**Comment by drdhaval2785** [comment]
@lakshmibsnt, kindly see https://ambuda-org.github.io/vidyullekha/?tab=dhatu&dhatu=07.0017&activePada=%7B%22text%22%3A%22Bokzyate%22%2C%22type%22%3A%22tinanta%22%2C%22args%22%3A%7B%22dhatu%22%3A%7B%22code%22%3A%2207.0017%22%2C%22upadesha%22%3A%22Bu%5C%5Cja%7E%22%2C%22upadeshaQuery%22%3A%22Buja%7E%22%2C%22artha%22%3A%22pAlanAByavahArayoH%22%7D%2C%22lakara%22%3A%223%22%2C%22prayoga%22%3A0%2C%22purusha%22%3A%220%22%2C%22vacana%22%3A%220%22%2C%22pada%22%3A%221%22%2C%22sanadi%22%3Anull%2C%22upasarga%22%3Anull%7D%7D

This seems to have been handled in vidyut library.
