### ISSUE TITLE
भवतु/भवतात् - भू धातोः लोट्-प्रथम-एकवचनम्

### ISSUE THREAD

**Issue by sridharb1** [drdhaval2785/prakriya#209]
महोदय,

किमर्थं जश्त्वं न भवेत्।
पदान्ते अस्ति, झलां जशोऽन्ते ८।२।३९॥ तु भवितुम् अर्हति

भवतात् -> भवताद्

अनन्तरम् - 
वाऽवसाने		८।४।५६॥ सूत्रेण भवतात् विकल्पेन पुनः आगच्छति

धन्यवादः
श्रीधरः

**Comment by drdhaval2785** [comment]
I think you are right. What is your say, @mrudani?

**Comment by sridharb1** [comment]
You are closing it as it is handled (correctly) in the other prakriya? Doesn't it need to be corrected here as well? Or is there a plan to transition to the other one?

**Comment by drdhaval2785** [comment]
There is a plan to integrate the other prakriya in ashtadhyayi.com. Therefore, I am declutterring the issues so that the next generator can focus on only the pending issues.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin Is the frontend for demo of the prakriya generator which is being considered to replace my generator.
