### ISSUE TITLE
Link in error message broken

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#21]
Link returned in error message when form is not found ("https://github.com/drdhaval2785/sktderivation/issues") is broken. Did you want it to point to SanskritVerb/issues?

**Comment by drdhaval2785** [comment]
![capture](https://user-images.githubusercontent.com/5755132/34140620-fb38e698-e4a1-11e7-9422-cfa7a0a5555b.png)

Fixed the error.
