### ISSUE TITLE
सु (षु॒ञ् अभिष॒वे) धातोः लोट्-उत्तम-एकवचनम्

### ISSUE THREAD

**Issue by sridharb1** [drdhaval2785/prakriya#210]
अहं चिन्तयामि यत् एषा प्रक्रिया भवनीयम्

१.	षु॒ञ् अभिष॒वे
[...]
५.	सु		धात्वादेः षः सः		६।१।६४॥
६.	सु लोँट्		लोँट् च		३।३।१६२॥
[...]
९.	सु इट्		तिप्तस्झिसिप्थस्थमिब्वस्मस् तातांझथासाथांध्वमिड्वहिमहिङ्	३।४।६९॥
[...]
१७.	सु श्नु इट्		स्वादिभ्यः श्नुः		३।१।७३॥
[...]
२०.	सु नु इट्		सार्वधातुकमपित्		१।२।४॥
२१.	सु नु इट्		क्ङिति च		१।१।५॥
२२.	सुन् व् इट्		हुश्नुवोः सार्वधातुके	६।४।८७॥
२३.	सुन्व् इट्		अचोऽन्त्यादि टि	१।१।६४॥
२४.	सुन्व् ए		टित आत्मनेपदानां टेरे	३।४।७९॥
२५.	सुन्व् आट् ए		आडुत्तमस्य पिच्च	३।४।९२॥
२६.	सुन्व् आ ए		हलन्त्यम्		१।३।३॥
२७.	सुन्व् आ ऐ		एत ऐ		३।४।९३॥
२८.	सुन्व् ऐ		आटश्च		६।१।९०॥
२९.	सुन्वै

तस्य भेदः #२२ मध्ये अस्ति. तत् नास्ति चेत्, तस्य प्रक्रियां अवगच्छामि

३०.    सुनु इट्        अचोऽन्त्यादि टि    १।१।६४॥
३१.    सुनु ए        टित आत्मनेपदानां टेरे    ३।४।७९॥
३२.    सुनु आट् ए        आडुत्तमस्य पिच्च    ३।४।९२॥
३३.    सुनु आ ए        हलन्त्यम्        १।३।३॥
३४.    सुनु आ ऐ        एत ऐ        ३।४।९३॥
३५.    सुनु ऐ        आटश्च        ६।१।९०॥
३६.    सु नो ऐ        सार्वधातुकार्धधातुकयोः    ७।३।८४॥
३७.    सुन् अव् ऐ        एचोऽयवायावः        ६।१।७८॥
३८.    सुनवै

किमर्थं हुश्नुवोः सार्वधातुके ६।४।८७॥ न वर्तते किञ्चित् स्पष्टी करोतु

कृपया लङ्-लकार-रूपम् अपि पश्यतु - तत्र असुन्वि (उत्तम-एकवचनम्) इति रूपम् भवति, अत्र किमर्थं नास्ति?

धन्यवादः
श्रीधरः

**Comment by drdhaval2785** [comment]
I am unable to understand the questions. Kindly elaborate what is the issue and what is the grammatical stand of grammarians.

**Comment by sridharb1** [comment]
The last few steps of the prakriya for सु (षु॒ञ् अभिष॒वे) धातोः लोट्-उत्तम-एकवचनम् which ends in  सुनवै is shown starting in #30 above. I understand how that is derived.

However, my question is that this is possible only if you do not do #22. If you do that, the prakriya takes a different form and ends in सुन्वै. Now, सुन्वै being wrong is not what I am arguing. I am asking why is #22 not applicable. If it is applicable, why don't we get a form like सुन्वै.

Thanks,
Sridhar

**Comment by drdhaval2785** [comment]
@mrudani,
Any comments or explanation on the question?

**Comment by drdhaval2785** [comment]
https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/mA882.html provides the following explanation

`आटि पित्वादङित्वात् यणं बाधित्वा गुणः`.

When there is succeeding 'आट्', because of पित्त्व, there is no यण्, but गुण happens.

**Comment by drdhaval2785** [comment]
Hope this satisfies your query.

**Comment by sridharb1** [comment]
Thank you. It does. Closing the issue.
