### ISSUE TITLE
अ॒दँ लिँट्-परस्मैपदी-प्रथमपुरुष-एकवचनम्

### ISSUE THREAD

**Issue by sridharb1** [drdhaval2785/prakriya#211]
लिटि, अद्-धातोः द्वे रूपे भवतः खलु?

एतत् रूपं न लब्धम्, परिशीलयतु महोदय!

![image](https://github.com/drdhaval2785/prakriya/assets/13346687/f0b5d94e-5b71-41a5-95a4-9baf7ee26bbf)

**Comment by drdhaval2785** [comment]
Just a small note. I have stopped maintaining this repository.

**Comment by sridharb1** [comment]
अस्तु महोदय, धन्यवादः

**Comment by drdhaval2785** [comment]
For more updated / supported version, kindly visit the following. https://ambuda-org.github.io/vidyullekha/

I checked at the following
https://ambuda-org.github.io/vidyullekha/?dhatu=02.0001&tab=tin

It seems to support the dual forms of ‘ad’ verb.

**Comment by sridharb1** [comment]
🙏
