### ISSUE TITLE
Prakriyas for verb forms are not loading

### ISSUE THREAD

**Issue by slabhyankar** [drdhaval2785/prakriya#212]
Wanted to get Prakriyas for तिष्ठति, भवति. 
No luck at ashtadhyayi-dot-com.
Where else can I check, please ?

**Comment by drdhaval2785** [comment]
https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=zWA&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&jsonmode=0&cond11=2&cond15=2&number=01.1077&removed_sutras=&step=11&type=tiGanta

You can try at https://www.sanskritworld.in/sanskrittool/SanskritVerb/ and fill required information

**Comment by slabhyankar** [comment]
Many thanks Dr. Dhaval, for your prompt response.
By the way, Merry Christmas ! Season's Greetings !! Happy New Year !!!
I still have a question -
You have clarified that ष्ठा becomes स्ठा by धात्वादेः षः सः (6.1.64
<https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/allsutrani/6.1.64.htm>
)
But how, by what सूत्रम् does स्ठा become स्था ?
Cordially, S. L. Abhyankar

**Comment by drdhaval2785** [comment]
It is by a paribhAshA “nimittApAye naimittikApAyaH”

**Comment by slabhyankar** [comment]
Is निमित्तापाये नैमित्तिकापायः any परिभाषा-सूत्रम् ?
यद्येतत् अष्टाध्याय्यां परिभाषा-सूत्रम्, कः क्रमाङ्कः खलु ?
ashtadhyaayi-dot-com इत्यत्र तु न प्राप्तम्
Cordially, S. L. Abhyankar
