### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by chakrabortydeepro** [drdhaval2785/prakriya#24]
Hello,
I found a wrong spelling of the word "क्षेपणे"
Reference: अ॑सुँ॑ क्षेपने

**Comment by drdhaval2785** [comment]
Thanks for the report. Will notify here when corrected.

**Comment by drdhaval2785** [comment]
vidyut-prakriya handles this. See https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=04.0106
