### ISSUE TITLE
Don't escape unicode devanAgarI

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/prakriya#25]
Reference and context: https://github.com/drdhaval2785/prakriya/issues/16#issuecomment-352645383

**Comment by drdhaval2785** [comment]
This does not seem a possibility.
JSON specs say that it will be converted to such fo.
So all default json encoders encode it such.
If you can specify the step by step guide, I can try it.

**Comment by vvasuki** [comment]
Did you try the fix suggested in my comment? Just in case you did not, let me restate it concisely:

Please pass these extra parameter to your jsonify call: `encoding="utf-8"`

**Comment by drdhaval2785** [comment]
@vvasuki

I tried. It gives the same result. I would welcome a PR if you can get it to work.

**Comment by vvasuki** [comment]
namaste @drdhaval2785 .

The below works in python3 (I just tried)  - 
```
>>> x
{'some_key': 'राम'}
>>> flask.json.dumps(x, indent=2, ensure_ascii=False)
'{\n  "some_key": "राम"\n}'
```

(You are on python3 right? If not you ought to switch.)

**Comment by gasyoun** [comment]
> python3

2 was before.

**Comment by drdhaval2785** [comment]
Done. Thanks @avinashvarna
