### ISSUE TITLE
par@56-1 not found in sutrainfo.json

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#27]
I was trying to convert the files to babylon as an exercise (and an early Xmas gift for @vvasuki  ;-)), and ran into the following error:
asnasizuH.json has
"sutra_num": "par@56-1",
in one of the steps in the derivation.

This sutra_num is not in the sutrainfo.json file, which causes an error. https://api.sanskritworld.in/v0.0.2/verbforms/slp1/asnasizuH?output_transliteration=devanagari also returns internal error.

I ran a script to go through all the steps of the derivations for all 220K forms and identify any missing sutra_nums and this was the only one missing.

**Comment by avinashvarna** [comment]
We can add this as a test if you enable continuous integration (e.g. travis-ci.org) so that if any forms are added in the future, the test will ensure that sutra info is not missing.

**Comment by vvasuki** [comment]
आह् - [यक्षराजस्मरणम्](https://kashcidvipashcit.wordpress.com/2015/12/25/digesting-santa-claus/) अपि सफलम्! ॐ वैश्रवणाय स्वाहा! अत्र केचन तत्प्रजा इत्यनुमामि सगृहाश्चेदपि :-)

**Comment by drdhaval2785** [comment]
@avinashvarna 
I ran a [script](https://github.com/drdhaval2785/SanskritVerb/blob/master/scripts/test_sutrainfo.py) on the two scripts [panini.php](https://github.com/drdhaval2785/SanskritVerb/blob/master/panini.php) and [function.php](https://github.com/drdhaval2785/SanskritVerb/blob/master/scripts/function.php) which actually generated sutrainfo.json and the data stored in derivation*.tar.gz.
I have updated the shell script which generates sutrainfo.json. https://github.com/drdhaval2785/SanskritVerb/blob/master/jsongenerator.sh#L20
This way, at the generation step itself the error will be thwarted.


My run of script gave me the following missing items. Some of them may not have been necessary for tinantas and not have caused problem. May pose problems in sandhi / subanta / other modules.
```
Missing items in sutrainfo.json
set(['eranekAc', '6.1.`09', 'dfn', '6.1,93', 'par@56-1', 'allopsTan'])
```

Two are  clearly typos i.e. '6.1.`09', '6.1,93'
Rest four I will have to see and correct.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/prakriya/commit/6be7bf6afd7b14862e662f72efd64c2e5fd1c078 after this commit you should be able to do your work @avinashvarna

**Comment by drdhaval2785** [comment]
The rest entries are also corrected on SanskritVerb repository.
Will be integrated in the next version of data.

**Comment by avinashvarna** [comment]
New version of sutrainfo works.
