### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#28]
I want input high (even higher than now) above. Output - just bellow (much higher).

Blocks like:
```
Implementation Notes
This function reads the pregenerated JSON files. If the JSON file exists, it is loaded back. If the file is absent, an error is thrown. The JSON files are created by the script at SanskritVerb repository. See https://github.com/drdhaval2785/SanskritVerb/blob/master/jsongenerator.sh for details.
```

```
Response Messages
Curl
Request URL
```

Doen't make much sense, so I would put them bellow `Response Body` and maybe even hide by default. Otherwise I have to scroll jus to see the results - no good.

![api](https://user-images.githubusercontent.com/80761/34643221-9a429eb2-f331-11e7-9929-5f2df62769ed.PNG)

**Comment by vvasuki** [comment]
What you're seeing is not a UI which dhaval or some other contributor has coded or can change easily.

You should use and suggest changes to https://avinashvarna.github.io/prakriya/ (by @avinashvarna ) instead.

**Comment by drdhaval2785** [comment]
This is an API documentation (swagger documentation) which is autogenerated from code because of flask-restplus library. It gives a framework to read the documentation and play with API. It is not UI. UI which is developed by Avinash around this API us very user friendly. Give it a try.

**Comment by gasyoun** [comment]
> UI which is developed by Avinash around this API us very user friendly

Indeed.
