### ISSUE TITLE
Response Body

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#30]
In the derivation window at https://api.sanskritworld.in/#!/default/get_full_data  I can see only 4 steps at once (far too little), like:

```
  {
        "form": "asam̐",
        "sutra": "bhūvādayo dhātavaḥ",
        "sutra_num": "1।3।1"
      },
      {
        "form": "asam̐",
        "sutra": "upadeśe'janunāsika it",
        "sutra_num": "1।3।2"
      },
      {
        "form": "as",
        "sutra": "tasya lopaḥ",
        "sutra_num": "1।3।9"
      },
      {
        "form": "as",
        "sutra": "sanādyantā dhātavaḥ",
        "sutra_num": "3।1।32"
      },
```

I would want to see stats - how many total steps. And the number of each step.

What is `"sutra_num": "-2"`?

Why are sutras no interlinking to a place with commentary, like why is `"sutra_num": "6।4।111"` plain text only?

I see `"derivation"` tree twice. What does it mean? Two possible ways for `syāma` or for every possible verb form? Sometimes 1 or 3?
I can visually hardly find end of 1st, but it should be easy to do.

At 

```
"dhatupradipa": "http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-15-03-2017//XA754.html",
    "gana": "adādi",
    "it_id": "",
    "it_status": "",
    "it_sutra": "",
    "jnu": "http://sanskrit.jnu.ac.in/tinanta/tinanta.jsp?t=193",
    "kshiratarangini": "http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-15-03-2017//kRi737.html",
    "lakara": "vidhiliṅ",
    "madhaviya": "http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-15-03-2017//mA715.html",
    "meaning": "bhuvi",
    "number": "02।0060",
    "padadecider_id": "parasmaipadī",
    "padadecider_sutra": "",
    "purusha": "uttama",
    "suffix": "mas",
    "uohyd": "http://sanskrit.uohyd.ac.in/cgi-bin/scl/skt_gen/verb/verb_gen.cgi?vb=as2_asaz_axAxiH_Buvi&prayoga=karwari&encoding=WX&upasarga=-&paxI=parasmEpaxI",
    "upasarga": "",
    "vachana": "bahu",
    "verb": "अ॑सँ॑",
    "verbslp": "asa!"
```

Nothing is said if it's an iT root, right?

**Comment by drdhaval2785** [comment]
> I can see only 4 steps

This is JSON output Marcis. A user readable output is available at https://avinashvarna.github.io/prakriya/.

**Comment by drdhaval2785** [comment]
> stats

Write a wrapper around API and get whatever stats you want.

**Comment by drdhaval2785** [comment]
> Two possible ways for syāma or for every possible verb form? Sometimes 1 or 3?

All possible ways to derive the given verb form.

> I can visually hardly find end of 1st, but it should be easy to do.

Check BavitA on Avinash's UI. It gives properly segmented result.

**Comment by drdhaval2785** [comment]
> What is "sutra_num": "-2"?

An artificial number added to display the messages which are not sUtra, vArtika or paribhAshAs.

**Comment by drdhaval2785** [comment]
> interlinking to a place with commentary

Will add a link to ashtadhyayi commentaries in API. Pursuing in separate issue.

**Comment by drdhaval2785** [comment]
> Nothing is said if it's an iT root

If the given verb form has iDAgama, it will have some results. Try with BavitA or eDitA.

**Comment by gasyoun** [comment]
> display the messages

How many different are there?

**Comment by drdhaval2785** [comment]
There are four such cases.
1. $vdata
2. $miscdata
3. $paribhASAdata
4. $otherdata

These four variables from https://github.com/drdhaval2785/SanskritVerb/blob/master/scripts/function.php
