### ISSUE TITLE
Add link to avinash's UI from swagger docs.

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/prakriya#33]
Will introduce folks who stumble upon the latter to the former,

(fyi @avinashvarna )

**Comment by avinashvarna** [comment]
Perhaps in the README as well. 
We could also move the UI into this repo itself, under docs. and serve it from there. I will submit a PR when I have some more time.

**Comment by drdhaval2785** [comment]
Sure. The PR would be welcome.
The Swagger docs now refer to @avinashvarna 's UI.
README maybe updated once @avinashvarna completes the PR, so that all changes may be documented.
Keeping open till then.

**Comment by drdhaval2785** [comment]
Swagger docs now has this reference.
![capture](https://user-images.githubusercontent.com/5755132/34906451-1e7d48fa-f894-11e7-9036-a399658b3a71.png)
