### ISSUE TITLE
cākarmakebhyaḥ। (3.4.69)

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#34]
No need for danda in IAST. Tested `gaccha`

laḥ karmaṇi ca bhāve cākarmakebhyaḥ। (3.4.69) -> laḥ karmaṇi ca bhāve cākarmakebhyaḥ (3.4.69)

https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=04.0106

Handles this
