### ISSUE TITLE
vā'vasāne

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#35]
Not typographically good.

vā'vasāne (8.4.56) -> vā‘vasāne (8.4.56)

**Comment by drdhaval2785** [comment]
Display may take care of this. Don't think that this calls for changes in data or API.

**Comment by drdhaval2785** [comment]
@avinashvarna may like to comment.

**Comment by avinashvarna** [comment]
I don't recognize the specific character proposed as a replacement. Is that a unicode character? Right now, the UI just displays the data returned by the API. I can update the UI to do a search & replace, but what is the expected IAST symbol for avagraha?

**Comment by drdhaval2785** [comment]
Not worthwhile to change.
