### ISSUE TITLE
paragraph mode

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#36]
Line mode as https://avinashvarna.github.io/prakriya/ has it is nice, in column:

![line](https://user-images.githubusercontent.com/80761/34667883-fc3a6118-f47b-11e7-9945-bbbf344fd104.PNG)

But to copy-paste it into an article or on web - not too convenient. For that I would think of a paragraph mode. As https://www.quora.com/What-is-the-meaning-of-the-name-Kaveri/answer/Nityanand-Misra has here:
```
kavera → tasyedam (4.3.120) → kavera + aṇ → tasya lopaḥ (1.3.9) → kavera + a → taddhiteṣvacāmādeḥ (7.2.117) → kāvera + a → yasyeti ca (6.4.148) → kāver + a → kāvera → ṭiḍḍhāṇañdvayasajdaghnañmātractayapṭhakṭhañkañkvarapaḥ (4.1.15) → kāvera + ṅīp → tasya lopaḥ (1.3.9) → kāvera + ī → yasyeti ca (6.4.148) → kāver + ī → kāverī.
```

**Comment by drdhaval2785** [comment]
@gasyoun Can you pursue UI specific items at https://github.com/avinashvarna/avinashvarna.github.io/issues ?
