### ISSUE TITLE
API from verb+tense / verb+suffix -> verb form

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#39]
https://github.com/drdhaval2785/prakriya/issues/37#issuecomment-356149552 suggested a possibility of verb form generation (as compared to current verb form analysis mode).

Live generation is possible via - https://www.sanskritworld.in/sanskrittool/SanskritVerb/tiGanta.html
Input verb, tense and select JSON mode.
https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=BU&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&jsonmode=1&cond11=2&number=01.0001&removed_sutras=&step=11&type=tiGanta for example.
But this will require quite a bit of refactoring.

Other possibility - Current data which is being used by the prakriya package and API can be read and rearranged to work in reverse direction and the same may be stored and used in future usage of API and package. This is more convenient and easy.

**Comment by avinashvarna** [comment]
I would suggest that you just put all the data in a properly indexed database, which can then be queried in many different ways to retrieve the same data. The current file organization structure can be thought of as a database indexed by the final form. If the index also includes verb/tense/suffix/etc., then the form can be quickly retrieved.

This is quite simple to do using SQL databases, but @vvasuki does not recommend SQL in his experience.

For NoSQL databases, in couchdb, you can create indexes using views (http://guide.couchdb.org/draft/cookbook.html). Some python database packages such as [CodernityDB](http://labs.codernity.com/codernitydb/) also allow sophisticated indexing schemes. I don't have too much experience in this area, and @vvasuki may have better suggestions.

**Comment by vvasuki** [comment]
Also related is https://github.com/drdhaval2785/SanskritVerb/issues/1056 (oftentimes, one needs to programatically access several tinanta forms without too much delay). Given that, an efficient access method (in case of a py library) or an API (in case of a REST service) might just do the following when one wants to get bhU + tip in laT parasmai: 

* Look up the conjugation table for bhU (in a O(1) operation PS: @drdhaval2785 you are familiar with https://en.wikipedia.org/wiki/Big_O_notation ? if not slurp it up - very useful CS jargon), and 
* then serially search for the appropriate form from that table (in constant time relative to number of dhAtus).

The first step may be accomplished with a simple flat file structure similar to what we have in case of prakriyA. Or, one may use databases as suggested by @avinashvarna (I'll gladly set up @drdhaval2785 's  access to vedavaapi.org:5984/_utils/ as needed ). I prefer the former, though for its low-dependency simplicity, the ability to have a ready dump of all conjugations and better ability to cater to mass access needs ("Give me all the bhU + laT forms now, and do it quick") .

**Comment by avinashvarna** [comment]
The flat file structure works for specific purposes but does not scale very well. For example, let's say we want to later be able to answer questions of the type "Find all forms where sutra x.y.z is used in the derivation". We would have to create an index from sutra num to file names in addition to dhAtu --> file names. This is what databases are designed for and it would make sense to reuse them instead of reinventing our own indexing scheme.

> better ability to cater to mass access needs ("Give me all the bhU + laT forms now, and do it quick") .

Why is this not possible with a database? (you said this is one of the reasons you prefer the flat file structure)

**Comment by vvasuki** [comment]
> The flat file structure works for specific purposes but does not scale very well. For example, let's say we want to later be able to answer questions of the type "Find all forms where sutra x.y.z is used in the derivation". 

True - I did not imagine us addressing such a need, since this was about just getting the final form given a clear vivaxA. If we really are shooting for such (??), then going hammer and tongs makes more sense.

> >     better ability to cater to mass access needs ("Give me all the bhU + laT forms now, and do it quick") .
> Why is this not possible with a database? (you said this is one of the reasons you prefer the flat file structure)

First let me clarify that I was referring to an atomic level db (one db tinanta form per db item), and not a clustered forms db (an entire lakAra or dhAtu per db item). I had intended to include the latter in my comment, but forgot (I'll go back and edit it for clarity).

It's possible, but possibly slower. Suppose you're asking for n-forms -  with an atomic db you need n lookups. With a clustered forms db (implementable easily with files), you need just 1 lookup operation.

**Comment by avinashvarna** [comment]
@vvasuki Is [this](https://github.com/avinashvarna/prakriya/blob/master/data/dhaval_prakriya_forms.zip) what you were asking for in https://github.com/drdhaval2785/SanskritVerb/issues/1056? The csv file can be converted to any form you want.

**Comment by avinashvarna** [comment]
Actually looks like http://www.sanskritworld.in/public/sanskrittool/SanskritVerb/generatedforms/verbformsdeva.tar.gz is similar, so maybe duplicated effort :(.

**Comment by avinashvarna** [comment]
P.S. The forms are in whatever order the files within the tar.gz were listed, but if this csv file is useful, I can change the script to sort the forms in some consistent manner.

**Comment by vvasuki** [comment]
(Responded to @avinashvarna at https://github.com/drdhaval2785/SanskritVerb/issues/937 )

**Comment by drdhaval2785** [comment]
@avinashvarna 
Thanks for drawing my attention to the verbforms csv. 
It is true - You are your best collaborator after six months. I had forgotten altogether about existence of that file.
This CSV (maybe in slp1) will be useful to tag the verb forms to their parent verbs + lakara + suffices.

So the workflow will be - 
1. Get verb + lakara + [suffix] -> verbform map.
2. Use the verbform.json (existing) to give the step by step derivation.

There are two issues which I can forsee.
1. The verbs stored in the database are with anusvAras, qu, wu, halanta etc. e.g qupaca!z, eDa~, YimidA! etc, whereas the user will enter only pac, eD, mid etc.
2. Some verbs have some premodifications happenning e.g. aci~ -> aYc. It may be slightly difficult to capture these two differences.
One possible way to overcome these issues -
1. In SanskritVerb, we provide the user with prepopulated valid verbs in autocomplete. Similarly the user can be given a prepopulated autocomplete in the UI. When the user writes eD he will be given option of eDa~.
2. For python package, the situation will be a bit trickier. Maybe we can use edit-distance or something similar to arrive at the desired verb. Not sure yet.

**Comment by avinashvarna** [comment]
I agree that providing an autocomplete in the UI is a really good solution. That way users can chose the correct option.

For the python API, it could expose an additional function to first find the closest match to a given dhAtu (as you say, either using edit-distance, or comparing with the closest form after अनुबन्धलोप), and offer the choices to the user. A second function could then lookup the right form for a given dhAtu.

**Comment by drdhaval2785** [comment]
Fresh CSV file
[generatedcsv.tar.gz](https://github.com/drdhaval2785/prakriya/files/1621265/generatedcsv.tar.gz)

**Comment by drdhaval2785** [comment]
Scriptlet to generate the required mapforms.json file 
```
result = {}
with open(os.path.join(appdata, 'generatedcsv11012018.csv')) as csvfile:
    reader = csv.DictReader(csvfile, ['verbform', 'verb', 'lakara',
                                      'suffix', 'number'])
    counter = 1
    for row in reader:
        verbform = row['verbform']
        verb = row['verb']
        lakara = row['lakara']
        suffix = row['suffix']
        number = row['number']
        if verb not in result:
            result[verb] = {}
        if lakara not in result[verb]:
            result[verb][lakara] = {}
        if suffix not in result[verb][lakara]:
            result[verb][lakara][suffix] = []
        result[verb][lakara][suffix].append((verbform, number))
        print counter
        counter += 1
    json.dump(result, open(os.path.join(appdata, 'lovely.json'), 'w'))
```

**Comment by vvasuki** [comment]
> Get verb + lakara + [suffix] -> verbform map.

I think that it is sufficient for the API or library function to just return the final form (bhuu + laT+ tip -> bhavati). The interested client can make a second call to the existing API or library function to get the step-by-step derivation for that form. Otherwise, we have less useful ("bad") abstraction.

**Comment by drdhaval2785** [comment]
A valid point.

**Comment by avinashvarna** [comment]
Small tip: You can use [collections.defaultdict](https://docs.python.org/2/library/collections.html#collections.defaultdict) to avoid having to write:
```python
        if verb not in result:
            result[verb] = {}
```

**Comment by drdhaval2785** [comment]
This is added in v0.0.5.

Will keep this open till this is stable.

**Comment by drdhaval2785** [comment]
@avinashvarna and @vvasuki 

The API at https://api.sanskritworld.in/#!/default/get_gen_data has started serving the verb forms for given verb, lakAra, purusha and vachana.

The website is having some trouble, so if you get no response from server, please be patient. It will be auto corrected in some time. But the API is working well now.

**Comment by vvasuki** [comment]
Nice! Await the python library version of this. In the meantime, regarding the API itself: 

*‌ Please include an example for Verb as well, and add a link to a list of valid values (eg: a column in the spreadsheet generated by @avinashvarna ).

* A more facile API would take as input a conjugated form such as yAwi. Take this API for example: https://api.vedavaapi.org/scala/grammar/v1/generators/alternateFormsWx/yAwi/karwari/lot/pra/1/parasmEpaxI . This avoids the need for having to know the exact acceptible verb root ("should one include the artha, or anubandha-s or anunAsika-s?" type confusion will be avoided.) This applies to the corresponding python library as well.

* Please keep in mind REST API conventions. Rethink using the verb `generate`.

* Fix the order of the fields displayed in the swagger UI.

**Comment by drdhaval2785** [comment]
Nice! Await the python library version of this.


No need to wait. It already is available in library.
http://prakriya.readthedocs.io/en/latest/usage.html#generate-verb-forms for
documentation.

**Comment by vvasuki** [comment]
Nice @drdhaval2785 ! 

One ugly thing I notice: 
>>> from prakriya import Generate
>>> g = Generate()

Never use a verb name a class! Use a noun. Generator.

And a metacomment:
When you quote someone in github, format it appropriately. There are helpful icons on the top for that. For example:

> Nice! Await the python library version of this.

**Comment by drdhaval2785** [comment]
Regarding quoting, it was reply from mobile in gmail itself. Will try to use github as far as possible.

**Comment by avinashvarna** [comment]
Maybe it's just a personal preference, but I don't think using `__getitem__` in this manner fits the common convention in python. I've not seen `__getitem__` accept multiple arguments to select what is returned, with further overloading to accept different number of arguments with different meanings, . I feel that this should just be a function which takes arguments. E.g
```python
g[verb, tense, purusha, vachana]
g[verb, tense, suffix]
>>> g['BU', 'law', 'praTama', 'eka']
>>> g['BU', 'law', 'tip']
```
should really be
```python
g.get_form(dhatu, lakara, purusha=None, vachana=None, suffix=None)
g.get_form('BU', 'law', 'praTama', 'eka')
g.get_form('BU', 'law', suffix='tip')
```

This is **much** clearer from an API perspective. Within the function, you can then do
```python
if purusha is not None and vachana is not None:
    # lookup using purusha and vachana
elif suffix is not None:
    # lookup using suffix
else:
    # raise Exception
```

Same applies to the prakriya class as well. If you and @vvasuki agree, I can open a separate issue for the change.

**Comment by vvasuki** [comment]
I agree with https://github.com/drdhaval2785/prakriya/issues/39#issuecomment-359023719 . The suggested interface is more intuitive.

**Comment by gasyoun** [comment]
> The website is having some trouble, so if you get no response from server, please be patient.

Maybe ask for a Cologne server? But guess it's Python is outdated anyway.

**Comment by drdhaval2785** [comment]
There is only one point pending in this discussion i.e. instead of getitem, use of methods. Moving to separate issue
