### ISSUE TITLE
Input transliteration devanagari does not work

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#40]
E.g. https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/%E0%A4%AD%E0%A4%B5%E0%A4%A4%E0%A4%83?output_transliteration=devanagari

Looks like a unicode handling issues from error reproduced locally:
```python
line 164, in __getitem__
    verbform = verbform.decode('utf-8')
  File "utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by drdhaval2785** [comment]
Looks like we will have to change the HTML encoded string to unicode string
first and then do processing.

**Comment by drdhaval2785** [comment]
Fixed now.
Should work well.


On Fri, Jan 12, 2018 at 8:41 AM, Dhaval Patel <drdhaval2785@gmail.com>
wrote:

> Looks like we will have to change the HTML encoded string to unicode
> string first and then do processing.
>



-- 
Dr. Dhaval Patel, I.A.S
Collector and District Magistrate, Anand
www.sanskritworld.in

**Comment by avinashvarna** [comment]
Works correctly. Closing issue.
