### ISSUE TITLE
Generate -> Generator

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/prakriya#41]
This is to track https://github.com/drdhaval2785/prakriya/issues/39#issuecomment-358996614

>>> from prakriya import Generate
>>> g = Generate()

Never use a verb name a class! Use a noun. Generator.

**Comment by avinashvarna** [comment]
I would further recommend using VerbFormGenerator or something similar, since generator is a pseudo-keyword in python.

**Comment by gasyoun** [comment]
> since generator is a pseudo-keyword in python.

ogh!

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/python-prakriya/releases/tag/v0.1.0 completed this task. Uses VerbFormGenerator
