### ISSUE TITLE
Change interface from __getitem__ to a function

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/prakriya#42]
From https://github.com/drdhaval2785/prakriya/issues/39#issuecomment-359023719
change the interface for querying forms/prakriya in the respective classes to a function instead of using `__getitem__`
Possible interface:
```python
g.get_form(dhatu, lakara, purusha=None, vachana=None, suffix=None)
```

**Comment by drdhaval2785** [comment]
From v0.2.0, it is supported. Getitem changed to a function.
