### ISSUE TITLE
samkalayya case

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/prakriya#43]
![iast](https://user-images.githubusercontent.com/80761/35243773-277b0c52-ffcf-11e7-8697-0d9d074f9be9.PNG)

http://rigveda.us/pe/31.htm

sarvā:  samkalayya  sapta  ittaram  śatam  śākhānām  śrūyate

Should `samkalayya` not be found, @drdhaval2785?

**Comment by drdhaval2785** [comment]
It is not a तिङन्त. So not expected to be present.
