### ISSUE TITLE
सनाद्यन्ता धातवः is shown incorrectly

### ISSUE THREAD

**Issue by neeleshb** [drdhaval2785/prakriya#44]
This sutra gives the धातुसंज्ञा for the सनाद्यन्त-शब्दाः words only, not for all. (http://ashtadhyayi.com/sutraani/3/1/32)

Currently, many prarkiyas (at least the ones I checked) invoke this sutra unnecessarily.

Example:  First few steps of क्रीणीतः

भूवादयो धातवः 1|3|1
 हलन्त्यम् 1|3|3 
तस्य लोपः 1|3|9 
आदिर्ञिटुडवः 1|3|5 
तस्य लोपः 1|3|9 
सनाद्यन्ता धातवः 3|1|32 
...
We don't need सनाद्यन्ता धातवः 3|1|32  here. Interestingly, we don't see this in क्रीणाति.

**Comment by drdhaval2785** [comment]
Yes. Will fix ASAP. I also observed this in some forms.

**Comment by drdhaval2785** [comment]
vidyut-prakriya handles this correctly.
