### ISSUE TITLE
विद् (2 पप) लोट् उत्तमपुरुष forms are wrong

### ISSUE THREAD

**Issue by neeleshb** [drdhaval2785/prakriya#47]
They should be वेदानि, वेदाव, वेदाम, not विदानि विदाव विदाम. 

आडुत्तमस्य पिच्च makes the आट् aagama as पित्, and hence पुगन्तलघूपधस्य will cause a गुण.

**Comment by drdhaval2785** [comment]
There seems to be some issue. Current generations seem OK.

**Comment by drdhaval2785** [comment]
![screenshot_20180324-165746](https://user-images.githubusercontent.com/5755132/37863501-d77042f0-2f84-11e8-8423-08d01efeaa73.png)

**Comment by drdhaval2785** [comment]
It seems so. Let me investigate this. It is not designed to be out of sync. There must be some error in logic somewhere. Thanks for pointing out the divergence
