### ISSUE TITLE
इण् गतौ लोट् उत्तमपुरुष forms are wrong

### ISSUE THREAD

**Issue by neeleshb** [drdhaval2785/prakriya#48]
This seems somewhat similar to the previous issue (issue 47). The given forms are इयानि इयाव इयाम, correct forms are अयानि अयाव अयाम. सार्वधातुकार्धधातुकयोः will take precedence over अचि श्नुधातु causing गुणादेश.

https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/%E0%A4%87%E0%A4%AF%E0%A4%BE%E0%A4%A8%E0%A4%BF?output_transliteration=devanagari

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0040 handles this well.
