### ISSUE TITLE
हन्-हिंसागत्योः लोट्-उत्तमपुरुष's forms are wrong

### ISSUE THREAD

**Issue by Amogha-Rao** [drdhaval2785/prakriya#49]
I think the forms of हन्-हिंसागत्योः in लोट्-लकार-उत्तमपुरुषः should be हनानि , हनाव & हनाम  in एकवचनम् , द्विवचनम् & बहुवचनम्  respectively whereas it is given as घ्नानि घ्नाव घ्नाम. Please check. 
Apologies if I am wrong.

**Comment by ananthakrishna1967** [comment]
You are correct. According to आडुत्तमस्य पिच्च, उत्तमपुरुष forms have आ. आ gets गुण and it gets strong form हन् and then it applies to all numbers of उत्तमपुरुष. so हन्+आ+नि, व and म. So forms are हनानि, हनाव and हनाम

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0002 Handles this well
