### ISSUE TITLE
unable to load prakriya

### ISSUE THREAD

**Issue by rtamsatyam** [drdhaval2785/prakriya#52]
पठति (पठ् , लट्लकार-प्रथमपुरुष-एकवचनम्)

We are sorry, but this prakriya cannot be loaded right now. 

This typically means that the system that generates the prakriya is currently unavailable. 

Please check back later. Hopefully the system should recover soon. 

If the error persists, please report the issue here.

I must however say, I am so happy that this website has been so painstakingly made. My pranams to you all!

**Comment by drdhaval2785** [comment]
Seems like API server is down. Will restore ASAP. Thanks for the report.

**Comment by drdhaval2785** [comment]
@rtamsatyam

The site works now. Kindly check
