### ISSUE TITLE
Prakriya for विन्द्, मुञ्च्  etc is wrong for ङित् प्रत्ययाः

### ISSUE THREAD

**Issue by neeleshb** [drdhaval2785/prakriya#53]
The prakriya shows शे मुचादीनाम् followed by अनिदितां हलः उपधायाः क्ङिति, effectively getting rid of nakaar, resulting into forms like मुचन्ति (instead of मुञ्चन्ति), or विदन्ति (विन्दन्ति). 

See sample forms here http://ashtadhyayi.com/dhatu/06.0166?form=%E0%A4%AE%E0%A5%81%E0%A4%9A%E0%A4%A8%E0%A5%8D%E0%A4%A4%E0%A4%BF.

**Comment by drdhaval2785** [comment]
It seems to be some issue in automatic generation. Current version (generated on the fly) is showing correct forms.
https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=mucx%21&upasarga=&lakAra=law&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&jsonmode=0&cond11=2&number=06.0166&removed_sutras=&step=11&type=tiGanta

**Comment by neeleshb** [comment]
The URL I am using is -

https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/
मुचन्ति?output_transliteration=devanagari

If I replace मुचन्ति by मुञ्चन्ति in the above URL, it returns an error.

Is this an old API ? Should I be using a different one?

PS: The way website works is that all the forms are stored in the database,
and clicking a form send an API request to fetch the prakriya.

Thanks
Neelesh




On Sat, Aug 11, 2018 at 11:45 PM, Dr. Dhaval Patel <notifications@github.com

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=06.0166 handles this.
