### ISSUE TITLE
प्रक्रिया on your web site for तन्वन्ति 

### ISSUE THREAD

**Issue by jupiter1957** [drdhaval2785/prakriya#55]
I have a doubt in the following प्रक्रिया on your web site for तन्वन्ति – 
तन्वन्ति (तन् , लट्लकार-प्रथमपुरुष-बहुवचनम्)
तनुँ
→ तनुँ [भूवादयो धातवः 1|3|1 ]
→ तनुँ [उपदेशेऽजनुनासिक इत् 1|3|2 ]
→ तन् [तस्य लोपः 1|3|9 ]
→ तन् [सनाद्यन्ता धातवः 3|1|32 ]
→ तन् [लः कर्मणि च भावे चाकर्मकेभ्यः 3|4|69 ]
→ तन्+लँट् [वर्तमाने लट् 3|2|123 ]
→ तन्+लँट् [लस्य 3|4|77 ]
→ तन्+लँट् [हलन्त्यम् 1|3|3 ]
→ तन्+लँ [तस्य लोपः 1|3|9 ]
→ तन्+लँ [उपदेशेऽजनुनासिक इत् 1|3|2 ]
→ तन्+ल् [तस्य लोपः 1|3|9 ]
→ तन्+झि [तिप्तस्झिसिप्थस्थमिब्वस्मस् तातांझथासाथांध्वमिड्वहिमहिङ् 3|4|78 ]
→ तन्+झि [लः परस्मैपदम् 1|4|99 ]
→ तन्+झि [तिङस्त्रीणि त्रीणि प्रथममध्यमोत्तमाः 1|4|101 ]
→ तन्+झि [तान्येकवचनद्विवचनबहुवचनान्येकशः 1|4|102 ]
→ तन्+झि [शेषे प्रथमः 1|4|108 ]
→ तन्+झि [तिङ्शित्सार्वधातुकम् 3|4|113 ]
→ तन्+उ+झि [तनादिकृञ्भ्य उः 3|1|79 ]
→ तन्+उ+अन्ति [झोऽन्तः 7|1|3 ]
→ तन्+उ+अन्ति [सार्वधातुकमपित् 1|2|4]
→ तन्+व्+अन्ति [इको यणचि 6|1|77 ]
Here 6.4.77 अचि श्नुधातुभ्रुवां य्वोरियङुवङौ will not apply? 
The सूत्रार्थः says अजादिप्रत्यये परे "श्नु" इत्यस्य, धातुसंज्ञकस्य, तथा "भ्रू" इत्यस्य इवर्णान्त/उवर्णान्तस्य अङ्गस्य इयङ्-उवङ्-आदेशौ भवतः ।
The result will be similar in both cases but being Later 
Sutra I felt this only should apply, Please advise!
→ तन्+व्+अंति [नश्चापदान्तस्य झलि 8|3|24 ]
→ तन्वन्ति [अनुस्वारस्य ययि परसवर्णः 8|4|58 ]
→ तन्वन्ति
Thanks and Regards,
Paresh Dalal
12-23-2018

**Comment by drdhaval2785** [comment]
tan is neither ending with 'shnu' nor has 'i' or 'u' at end. So I do not
see any occassion for application of this rule.

**Comment by drdhaval2785** [comment]
Thank you for giving us an opportunity to serve you.
