### ISSUE TITLE
Prakria not loading

### ISSUE THREAD

**Issue by prasadkuppa** [drdhaval2785/prakriya#57]
Getting the following error message..

We are sorry, but this prakriya cannot be loaded right now.

**Comment by drdhaval2785** [comment]
We are working on it. Will be resolved soon. Thanks for report.

**Comment by drdhaval2785** [comment]
It is up and running now @prasadkuppa

**Comment by prasadkuppa** [comment]
धन्यवादः, महोदय ।

**Comment by prasadkuppa** [comment]
Namaste. This is broken again. Can you please look into it?

dhanyavAdAH

**Comment by drdhaval2785** [comment]
Working. I have not done anything. So server may have beem down because of too many hits. It is a small server

**Comment by prasadkuppa** [comment]
धन्यवादः महोदय ।

**Comment by prasadkuppa** [comment]
Namaste Mahodaya. It is not working again for the last couple of days. Can
you please help?

Regards,

Prasad

**Comment by drdhaval2785** [comment]
Working now.

**Comment by prasadkuppa** [comment]
DhanyavAdAH
