### ISSUE TITLE
10.0487 - क्षिप  - prakriya is NOT loading 

### ISSUE THREAD

**Issue by blueiris2005** [drdhaval2785/prakriya#58]
10.0487 - क्षिप 
चुरादिः  उभयपदी  अकर्मकः  सेट्
लट्लकारः (परस्मैपदम्) - क्षिपयति
--
prakriya is NOT loading for any लट्लकारः (परस्मैपदम्) - क्षिपयति / क्षिपयतः
OR for
लट्लकारः (आत्मनेपदम्) - क्षिपयते

**Comment by drdhaval2785** [comment]
@blueiris2005 

It seems that in our database, there is no kzipa curAdi. It is only kzipa~ tudAdi and divAdi.

Therefore, there is no such data being seen. If there is a conclusive proof of a curAdi verb kzipa, will try to incorporate.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=10.0487 handles this.
