### ISSUE TITLE
०१.०६७० इन्वाम्बभूव prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#60]
https://ashtadhyayi.com/dhatu/01.0670?form=%E0%A4%87%E0%A4%A8%E0%A5%8D%E0%A4%B5%E0%A4%A4%E0%A4%BF

इन्वाम्बभूव prakriya is not loading

**Comment by drdhaval2785** [comment]
They are known issues. Only cakAra would be displayed.
