### ISSUE TITLE
इन्वामास Prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#61]
०१.०६७० इन्वामास Prakriya is not loading

https://ashtadhyayi.com/dhatu/01.0670?form=%E0%A4%87%E0%A4%A8%E0%A5%8D%E0%A4%B5%E0%A4%A4%E0%A4%BF

**Comment by drdhaval2785** [comment]
This is a known issue. Only cakAra forms would be displayed
