### ISSUE TITLE
ऊषाम्बभूव prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#62]
०१.०७७९ ऊष्
https://ashtadhyayi.com/dhatu/01.0779?form=%E0%A4%8A%E0%A4%B7%E0%A4%A4%E0%A4%BF
ऊषाम्बभूव prakriya is not loading
Please also check several others in this page.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/issues/266

Known issue
