### ISSUE TITLE
ईषाम्बभूव Prakriya not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#63]
०१.०७८० ईष्
https://ashtadhyayi.com/dhatu/01.0780?form=%E0%A4%88%E0%A4%B7%E0%A4%A4%E0%A4%BF
ईषाम्बभूव Prakriya not loading
Please check other words also in this page.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritVerb/issues/266

Known issue
