### ISSUE TITLE
अशेक्ष्यत् prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#66]
०१.०७८३ शिष्
https://ashtadhyayi.com/dhatu/01.0783?form=%E0%A4%B6%E0%A5%87%E0%A4%B7%E0%A4%A4%E0%A4%BF
अशेक्ष्यत् prakriya is not loading
Please check other words also in this page.

**Comment by drdhaval2785** [comment]
01.0783 is सेट्
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0783 
Therefore, this form will not come.

However there is another dhAtu which is अनिट्. That is 07.0014
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=07.0014
