### ISSUE TITLE
ओषाञ्चकार prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#67]
०१.०७९२ उष्
https://ashtadhyayi.com/dhatu/01.0792?form=%E0%A4%93%E0%A4%B7%E0%A4%A4%E0%A4%BF
ओषाञ्चकार prakriya is not loading
Please check other words also in this page.

**Comment by drdhaval2785** [comment]
Should be ozAYcakAra. Shows uzAYcakAra in SanskritVerb

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0792 handles this.
