### ISSUE TITLE
तक्ष्णवाव Prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#71]
०१.०७४३ तक्ष्
https://ashtadhyayi.com/dhatu/01.0743?form=%E0%A4%A4%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A4%A4%E0%A4%BF
तक्ष्णवाव etc., Prakriya not loading
Please check other words also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0743 handles this.
