### ISSUE TITLE
स्तृक्षतम् Prakriya not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#72]
०१.०७५१ स्तृक्ष्
https://ashtadhyayi.com/dhatu/01.0751?form=%E0%A4%B8%E0%A5%8D%E0%A4%A4%E0%A5%83%E0%A4%95%E0%A5%8D%E0%A4%B7
स्तृक्षतम् etc., Prakriya not loading
Please check other words also in this page.

**Comment by vshylaja** [comment]
Prakriya error is also reported here
https://avinashvarna.github.io/prakriya/

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0751 handles this.
