### ISSUE TITLE
तितिक्षेरन् prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#75]
https://ashtadhyayi.com/dhatu/01.1126?form=%E0%A4%A4%E0%A4%BF%E0%A4%A4%E0%A4%BF%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A4%A4%E0%A5%87
०१.११२६ तिज्
तितिक्षेरन् prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
The सन् suffix is allowed in गुप्तिज्किद्भ्यः in three specific senses. For other cases, there are different forms. I need to add one lot. Ashtadhyayi.com needs to add another

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1126 handles this.
