### ISSUE TITLE
एठाम्बभूव prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#76]
https://ashtadhyayi.com/dhatu/01.0300?form=%E0%A4%8F%E0%A4%A0%E0%A4%A4%E0%A5%87
०१.०३०० एठ्
एठाम्बभूव prakriya is not loading
Please check other forms also in the same page.

**Comment by drdhaval2785** [comment]
@vshylaja kindly read my earlier remarks. babhUva and Asa forms will not be there for any verb. It is a known issue. Kindly do not raise issues about their absence again and again.
