### ISSUE TITLE
तिष्ठ prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#81]
https://ashtadhyayi.com/dhatu/01.1077?form=%E0%A4%A4%E0%A4%BF%E0%A4%B7%E0%A5%8D%E0%A4%A0
०१.१०७७ स्था
तिष्ठ prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1077 handles this.
