### ISSUE TITLE
स्तुवन्ति prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#83]
https://ashtadhyayi.com/dhatu/02.0038?form=%E0%A4%B8%E0%A5%8D%E0%A4%A4%E0%A5%81%E0%A4%B5%E0%A4%A8%E0%A5%8D%E0%A4%A4%E0%A4%BF
०२.००३८ स्तु
स्तुवन्ति prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
Forms generated by SanskritVerb are OK. Need to investigate why it is not packaged in prakriya package.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=02.0038 handles this.
