### ISSUE TITLE
वेहिषीयास्थाम् prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#85]
https://ashtadhyayi.com/dhatu/01.0730?form=%E0%A4%B5%E0%A5%87%E0%A4%B9%E0%A4%A4%E0%A5%87
०१.०७३० वेह्
वेहिषीयास्थाम् prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.0730 handles this.
