### ISSUE TITLE
शर्धतु, शर्धतात् prakriya are not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#87]
https://ashtadhyayi.com/dhatu/01.1014?form=%E0%A4%B6%E0%A4%B0%E0%A5%8D%E0%A4%A7%E0%A4%A4%E0%A4%BF
०१.१०१४ शृध्
शर्धतु, शर्धतात् prakriya are not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1014 handles this.
