### ISSUE TITLE
दीदांसितास्थः prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#88]
https://ashtadhyayi.com/dhatu/01.1149?form=%E0%A4%A6%E0%A5%80%E0%A4%A6%E0%A4%BE%E0%A4%82%E0%A4%B8%E0%A4%A4%E0%A4%BF
०१.११४९ दान्
दीदांसितास्थः prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?tab=tin&dhatu=01.1149 handles this.
