### ISSUE TITLE
input and output transliterations in paths

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#9]
https://github.com/drdhaval2785/prakriya/issues/6#issuecomment-352190114 suggested that we should have flexible input and output transliterations.
Seems a reasonable requirement.

Suggested URI
http://api.sanskritworld.in/v0.0.1/tinantas/slp1/jagAma/prakriya?encoding=devanaagarii

My preference
http://api.sanskritworld.in/v0.0.1/tinantas/input/slp1/output/devanagari/jagAma/prakriya

The inclination towards `?encoding=devanagarii` is less.
@vvasuki what do you think?
Is this as intuitive as you would want it to be?

indic_transliteration sancript is what I need for this.

**Comment by drdhaval2785** [comment]
> http://api.sanskritworld.in/v0.0.1/tinantas/input/slp1/output/devanagari/jagAma/prakriya

implemented now.

https://api.sanskritworld.in/v0.0.2/input/slp1/output/devanagari/jagAma/prakriya for example.
As there is not going to be subantas here. Currently not kept the word tinantas.

**Comment by vvasuki** [comment]
A couple of problems with the current version, @drdhaval2785 .

- You, the author, know that there's not going to be subanta-s here. A random person looking at the URL should know it as well. He won't know unless tinantas is in the url. Further, that would conform to the typical "resource" access URI conventions - http://www.restapitutorial.com/lessons/restfulresourcenaming.html .

- I think that the term adding the term input is a ok (though to anyone familiar with typical REST API conventions, URI path components refer to the resource), but it would be clearer if input_slp1 were used instead (if you wish to retain "input").

- output/devanAgarI should not be in the path. That should be in the query string. (Reason again is that it violates common expectations http://www.restapitutorial.com/lessons/restfulresourcenaming.html ). Perhaps output_encoding=devanagari would be good..

**Comment by vvasuki** [comment]
Rethinking along the lines of good URI conventions:

http://api.sanskritworld.in/v0.0.1/tinantas/slp1/jagAma/prakriyas/devanaagarii

is a fair alternative to 

http://api.sanskritworld.in/v0.0.1/tinantas/slp1/jagAma/prakriya?encoding=devanaagarii

suggested earlier

**Comment by drdhaval2785** [comment]
As far as I understand from various APIs such as api.github.com is that the APIs should be named as such that I can curtail something from the tail and still get some valid semantic idea.

> Suggested API - http://api.sanskritworld.in/v0.0.1/tinantas/slp1/jagAma/prakriyas/devanaagarii

Proposed API 
http://api.sanskritworld.in/verbforms/jagAma/prakriyas/slp1/devanaagarii

Expected Behaviour
http://api.sanskritworld.in/verbforms/jagAma/prakriyas/slp1/devanaagarii -> input in SLP1 and output in Devanagari
http://api.sanskritworld.in/verbforms/jagAma/prakriyas/slp1 -> input in SLP1 and output in default transliteration (I have slp1 in mind. Maybe Devanagarai too.)
http://api.sanskritworld.in/verbforms/jagAma/prakriyas -> input in default transliteration (slp1) and output in default transliteration (slp1/devanagari)
http://api.sanskritworld.in/verbforms/jagAma -> Whole info regarding jagAma in default input and output transliteration.
http://api.sanskritworld.in/verbforms -> list all valid verb forms. (A very long process). I think I will not support it for now.

1. tinantas -> vebforms. Will be free from transliterating issues. tiGanta / tiNanta ... and will be a proper English word.
2. Remove versioning from API. I do not intend to support multiple versions at one go. Swagger documentation will have the API version info.

@vvasuki What is your take?

**Comment by drdhaval2785** [comment]
I thought over it.
input_transliteration and output_transliteration filters can be applied to all the API calls and therefore they should be better kept as filters.

http://api.sanskritworld.in/verbforms/jagAma/prakriyas?input_transliteration=slp1&output_transliteration=devanaagarii -> input in SLP1 and output in Devanagari
http://api.sanskritworld.in/verbforms/jagAma?input_transliteration=slp1&output_transliteration=devanaagarii -> Whole info regarding jagAma.
http://api.sanskritworld.in/verbforms?input_transliteration=slp1&output_transliteration=devanaagarii -> List all valid verb forms. (A very long process). I think I will not support it for now.

**Comment by vvasuki** [comment]
As far as renaming tinanta-s to verbforms - seems fine.

Regarding moving input_transliteration to being a filter - not a good idea. Because the input_transliteration value is essential to make sense out of the jagAma portion of the path. So, just looking at http://api.sanskritworld.in/verbforms/jagAma wont tell you what's being asked for. In other words, unambiguously constructing that portion of the URI only - without the filters (which need to be optional) - is not possible.

http://api.sanskritworld.in/verbforms?input_transliteration=slp1&output_transliteration=devanaagarii - -> :-D The input_transliteration filter does not even make sense here. And you should just serve a file rather than doing any long computation.

**Comment by vvasuki** [comment]
Oh  wait - all is good, but where did the version number go? Good API is always versioned.

**Comment by drdhaval2785** [comment]
OK.
http://api.sanskritworld.in/v0.0.2/verbforms/slp1/jagAma/prakriyas?output_transliteration=devanaagarii

**Comment by vvasuki** [comment]
sgtm! (sounds good to me)

**Comment by drdhaval2785** [comment]
Implemented now.
