### ISSUE TITLE
वर्तिष्यते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#96]
https://ashtadhyayi.com/dhatu/01.0862?form=%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%A4%E0%A5%87
०१.०८६२ वृत्
वर्तिष्यते prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
Response from API is only for divAdi dhAtu. Not for bhvAdi dhatu. Needs to be investigated.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0862&tab=tin handles this.
