### ISSUE TITLE
 वर्धिष्यते prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#98]
https://ashtadhyayi.com/dhatu/01.0863?form=%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%A7%E0%A4%A4%E0%A5%87
०१.०८६३ वृध्
वर्धिष्यते prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
https://www.sanskritworld.in/sanskrittool/SanskritVerb/panini.php?first=vfDu%21&upasarga=&lakAra=lfw&sanAdi=&tran=SLP1&vAcya=kartR&frontend=1&jsonmode=0&cond11=2&number=01.0863&removed_sutras=&step=11&type=tiGanta generates this. 
Need to investigate why this is not stored in prakriya package.

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0863&tab=tin handles this.
